import{c as M,p as T}from"./assets/favorites-82848be3.js";import{i as h,a as v}from"./assets/vendor-4d8461fa.js";function k(){h.warning({id:"email-exists",class:"email-exists",message:"this email is already registered, pls choose another one.",theme:"dark",messageSize:"18px",messageColor:"#1B1B1B99",backgroundColor:"#EEA10C",color:"#EEA10C",position:"topRight",transitionIn:"fadeInLeft",transitionOut:"fadeOutRight",transitionInMobile:"fadeInLeft",transitionInMobile:"fadeOutRight",maxWidth:"390px",timeout:5e3,closeOnEscape:"true"})}function x(){h.error({id:"wrong-search-data",class:"wrong-search-data",message:"pls, enter correct data.",theme:"dark",messageSize:"18px",messageColor:"white",backgroundColor:"#dd1e08",color:"#dd1e08",position:"topRight",transitionIn:"fadeInLeft",transitionOut:"fadeOutRight",transitionInMobile:"fadeInLeft",transitionInMobile:"fadeOutRight",maxWidth:"390px",timeout:5e3,closeOnEscape:"true"})}function q(){h.success({id:"enter-success",class:"enter-success",message:"Great! You have successfully subscribed.",messageColor:"#1b1b1b",messageSize:"18px",messageLineHeight:"1.2",backgroundColor:"#F6F6F6",color:"#F6F6F6",maxWidth:"390px",position:"topRight",timeout:5e3,transitionIn:"fadeInLeft",transitionOut:"fadeOutRight",transitionInMobile:"fadeInLeft",transitionInMobile:"fadeOutRight",closeOnEscape:"true"})}v.defaults.baseURL="https://energyflow.b.goit.study/api";const O=document.querySelector(".switch-list"),w=document.querySelector(".exercises-list"),y=document.querySelector("#tui-pagination-container"),A=document.querySelector(".bp-form-wraper");let u=8,d=1,E="Muscles",F;O.addEventListener("click",P);function R(e,n){let t;return function(...r){const f=()=>{clearTimeout(t),e(...r)};clearTimeout(t),t=setTimeout(f,n)}}function I(){window.innerWidth<768?u=8:u=12}async function z({filter:e,page:n=1,limit:t=12,type:i}){try{return(await v.get(`/${i}`,{params:{filter:e,page:n,limit:t}})).data}catch{console.error("Something wrong")}}async function m(){A.classList.add("visually-hidden");try{const{page:e,totalPages:n,results:t}=await z({type:"filters",filter:E,limit:u,page:d});w.innerHTML=B(t),y.innerHTML="",n>1&&(F=M(y,n,d,u,H))}catch{}}function H(e){d=e,m()}async function P(e){if(e.preventDefault(),e.target.tagName!=="BUTTON")return;w.innerHTML="",d=1,E=e.target.dataset.filter,Array.from(e.currentTarget.children).map(i=>{i.textContent!==e.target.textContent?i.classList.remove("is-active"):i.classList.add("is-active")});try{await m()}catch{console.error("oops")}}function B(e){return e.map(({name:t,filter:i,imgUrl:r})=>`<li class="exercises-item" data-filter="${i}" data-name="${t}">         
          <div class="image-container">
            <img class="exercises-image" src="${r}" alt="${i}"/>
            <div class="text-container">
              <h3 class="exercises-title">${t}</h3>
              <p class="exercises-text">${i}</p>
            </div>
          </div>
         </li>`).join("")}window.addEventListener("load",()=>{I(),m()});addEventListener("resize",R(()=>{const e=u;I(),e!==u&&m()},250));document.addEventListener("DOMContentLoaded",async function(){const e=document.querySelectorAll(".switch-item"),n=document.querySelector(".exercises-list"),t=document.querySelector(".bp-list"),i=document.querySelector(".bp-form-wraper"),r=document.querySelector(".bp-search-input");for(let s=0;s<e.length;s++)e[s].addEventListener("click",async function(){e[s].dataset.filter,f();const o=r.value.trim().toLowerCase();p("Muscles","All",o)});function f(){t.innerHTML=""}async function p(s,o,a){const c=Array.from(t.children).filter(l=>l.textContent.toLowerCase().includes(a));c.length===0?C():S(c,t)}function C(s){t.innerHTML=`<p class="exercise-no-result">
              Unfortunately,  <span class="exercise-span"> no results</span> were
              found. You may want to consider other search options to find the
              exercise you are looking for. Our range is wide and you have the
              opportunity to find more options that suit your needs.
          </p>`}async function S(s,o){o.innerHTML="";for(let a=0;a<s.length;a++){const c=s[a],l=document.createElement("li");l.classList.add("bp-item"),l.dataset.id=c.dataset.id,l.innerHTML=c.innerHTML,l.addEventListener("click",function(){i.classList.remove("visually-hidden")}),o.appendChild(l)}}r.addEventListener("input",function(){const s=r.value.trim().toLowerCase();p("Muscles","All",s)}),document.getElementById("bp-form").addEventListener("submit",function(s){s.preventDefault();const o=document.querySelector(".switch-item.is-active").dataset.filter,a="All",c=r.value.trim().toLowerCase();p(o,a,c)}),n.addEventListener("click",function(s){s.target.closest(".exercises-item")&&(s.preventDefault(),i.classList.remove("visually-hidden"))}),e.forEach(s=>{s.addEventListener("click",function(){t.classList.contains("visually-hidden")||n.classList.remove("visually-hidden")})})});const g=document.querySelector("#subscribe-form"),L=document.querySelector("#footer-input"),$=/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;g.addEventListener("submit",async e=>{e.preventDefault();const n=g.elements.email.value.trim().toLowerCase();if(!n.match($)){L.style.borderColor="red",x();return}const t=await W(n);L.style.borderColor="#7e847f",t&&q(),g.reset()});async function W(e){try{return await T({email:e},"subscription")}catch(n){if(n.response.status===409){k();return}x()}}const b=document.querySelector(".scroll-up");window.addEventListener("scroll",function(){document.documentElement.scrollTop>20?b.style.display="block":b.style.display="none"});
//# sourceMappingURL=commonHelpers2.js.map
