import{c as E,p as O}from"./assets/modal-da940331.js";import{i as m,a as y}from"./assets/vendor-8c2391c4.js";function L(){m.warning({id:"email-exists",class:"email-exists",message:"this email is already registered, pls choose another one.",theme:"dark",messageSize:"18px",messageColor:"#1B1B1B99",backgroundColor:"#EEA10C",color:"#EEA10C",position:"topRight",transitionIn:"fadeInLeft",transitionOut:"fadeOutRight",transitionInMobile:"fadeInLeft",transitionInMobile:"fadeOutRight",maxWidth:"390px",timeout:5e3,closeOnEscape:"true"})}function S(){m.error({id:"wrong-search-data",class:"wrong-search-data",message:"pls, enter correct data.",theme:"dark",messageSize:"18px",messageColor:"white",backgroundColor:"#dd1e08",color:"#dd1e08",position:"topRight",transitionIn:"fadeInLeft",transitionOut:"fadeOutRight",transitionInMobile:"fadeInLeft",transitionInMobile:"fadeOutRight",maxWidth:"390px",timeout:5e3,closeOnEscape:"true"})}function M(){m.success({id:"enter-success",class:"enter-success",message:"Great! You have successfully subscribed.",messageColor:"#1b1b1b",messageSize:"18px",messageLineHeight:"1.2",backgroundColor:"#F6F6F6",color:"#F6F6F6",maxWidth:"390px",position:"topRight",timeout:5e3,transitionIn:"fadeInLeft",transitionOut:"fadeOutRight",transitionInMobile:"fadeInLeft",transitionInMobile:"fadeOutRight",closeOnEscape:"true"})}y.defaults.baseURL="https://energyflow.b.goit.study/api";const T=document.querySelector(".switch-list"),x=document.querySelector(".exercises-list"),b=document.querySelector("#tui-pagination-container"),k=document.querySelector(".bp-form-wraper");let a=8,r=1,w="Muscles",q;T.addEventListener("click",A);function z(e,t){let s;return function(...n){const c=()=>{clearTimeout(s),e(...n)};clearTimeout(s),s=setTimeout(c,t)}}function I(){window.innerWidth<768?a=8:a=12}async function R({filter:e,page:t=1,limit:s=12,type:i}){try{return(await y.get(`/${i}`,{params:{filter:e,page:t,limit:s}})).data}catch{console.error("Something wrong")}}async function o(){k.classList.add("visually-hidden");try{const{page:e,totalPages:t,results:s}=await R({type:"filters",filter:w,limit:a,page:r});x.innerHTML=$(s),b.innerHTML="",t>1&&(q=E(b,t,r,a,F))}catch{}}function F(e){r=e,o()}async function A(e){if(e.preventDefault(),e.target.tagName!=="BUTTON")return;x.innerHTML="",r=1,w=e.target.dataset.filter,Array.from(e.currentTarget.children).map(i=>{i.textContent!==e.target.textContent?i.classList.remove("is-active"):i.classList.add("is-active")});try{await o()}catch{console.error("oops")}}function $(e){return e.map(({name:s,filter:i,imgUrl:n})=>`<li class="exercises-item" data-filter="${i}" data-name="${s}">         
          <div class="image-container">
            <img class="exercises-image" src="${n}" alt="${i}"/>
            <div class="text-container">
              <h3 class="exercises-title">${s}</h3>
              <p class="exercises-text">${i}</p>
            </div>
          </div>
         </li>`).join("")}window.addEventListener("load",()=>{I(),o()});addEventListener("resize",z(()=>{const e=a;I(),e!==a&&o()},250));document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("bp-form"),t=document.querySelector(".bp-search-input"),s=document.querySelector(".bp-list"),i=document.querySelectorAll(".switch-item");let n=1,c=9,p="",v="";i.forEach(l=>{l.addEventListener("click",function(){i.forEach(u=>{u.classList.remove("is-active")}),this.classList.add("is-active"),p=this.textContent.trim()})}),e.addEventListener("submit",function(l){l.preventDefault();const u=t.value.trim().toLowerCase();s.innerHTML="",axios.get("/api/exercises",{params:{search:u,filter:p,subtype:v,page:n,limit:c}}).then(f=>{const g=f.data;g.length===0?iziToast.error({title:"No Results",message:"",position:"topCenter",timeout:5e3,closeOnClick:!0}):g.forEach(C=>{const h=document.createElement("li");h.textContent=C.name,s.appendChild(h)})}).catch(f=>{})})});const d=document.querySelector("#subscribe-form"),P=document.querySelector("#footer-input"),B=/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;d.addEventListener("submit",async e=>{e.preventDefault();const t=d.elements.email.value.trim().toLowerCase();if(!t.match(B)){P.style.borderColor="red",L();return}await H(t)&&M(),d.reset()});async function H(e){try{return await O({email:e},"subscription")}catch(t){if(t.response.status===409){L();return}S()}}
//# sourceMappingURL=commonHelpers2.js.map
